routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});


Route::middleware(['auth:sanctum', 'verified'])->prefix('assignments')->group(function () {
    Route::middleware('can:review applications')->group(function(){
        Route::get('/','App\Http\Controllers\ApplicationController@assignments')->name('assignments');

        Route::middleware('projectOfficer')->get('review/{application}',function (\App\Models\Application $application){
            return view('applications.review',[
                'application' => $application,
            ]);
        })->name('applications.review');
    });

});

Route::middleware(['auth:sanctum', 'verified'])->prefix('applications')->group(function () {
    Route::middleware('can:create applications')->group(function(){
        Route::get('/','App\Http\Controllers\ApplicationController@index')->name('applications');

//        Route::view('help','applications.help')->name('applications.help');

        Route::get('apply/{form}/about',function(\App\Models\ApplicationForm $form){
            return view('applications.about.index',[
                'applicationForm' => $form,
            ]);
        })->middleware('applicationWindowClosed')->name('applications.about');

//        Route::get('apply/{form}/guidance-document',function(\App\Models\ApplicationForm $form){
//            return Storage::disk('public')->download($form->guidance_document,Str::slug($form->name." "."Guidance Document").".pdf");
//        })->name('applications.guidance');
//
//        Route::get('apply/{form}/privacy-policy',function(\App\Models\ApplicationForm $form){
//            return view('applications.privacy.index',[
//                'applicationForm' => $form,
//            ]);
//        })->name('applications.privacy');

        Route::get('apply/{form}/data-usage-statement',function(\App\Models\ApplicationForm $form){
            return view('applications.data-usage-statement.index',[
                'applicationForm' => $form,
            ]);
        })->name('applications.data');

//        Route::get('apply/{form}/terms',function(\App\Models\ApplicationForm $form){
//            return view('applications.terms.index',[
//                'applicationForm' => $form,
//            ]);
//        })->name('applications.terms');

        Route::get('apply/{form}/eligibility',function(\App\Models\ApplicationForm $form){
            return view('applications.eligibility.index',[
                'applicationForm' => $form,
            ]);
        })->middleware('applicationWindowClosed')->name('applications.eligibility');

        Route::get('apply/{form}/closed',function(\App\Models\ApplicationForm $form){
            return view('applications.closed',[
                'applicationForm' => $form,
            ]);
        })->name('applications.closed');

        Route::get('apply/{form}/application/{application}',function (\App\Models\ApplicationForm $form,\App\Models\Application $application){
            return view('applications.apply',[
                'application' => $application,
            ]);
        })->middleware('applicant')->name('applications.apply');
    });


});

app/Models/Application.php
<?php

namespace App\Models;

use App\Http\Traits\Hashidable;
use App\Notifications\ApplicationRejectedNotification;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    use HasFactory;
    use Hashidable;

    protected $guarded = ['id'];

    protected $dates = ['submitted_at','resubmitted_at'];

    public static function boot() {
        parent::boot();

        static::deleting(function($application) {
//            if($application->isForceDeleting())
//            {


                $application->applicationResponses()->delete();
                $application->applicationNotes()->delete();
            //}
        });


    }

    public function applicationForm(){
        return $this->belongsTo('App\Models\ApplicationForm');
    }

    public function user(){
        return $this->belongsTo('App\Models\User');
    }

    public function applicationNotes(){
        return $this->hasMany('App\Models\ApplicationNote');
    }

    public function applicationResponses(){
        return $this->hasMany('App\Models\ApplicationResponse');
    }

    public function projectOfficers(){
        return $this->belongsToMany('App\Models\User','application_officer','application_id','user_id')->using('App\Models\Pivots\AssignmentsPivot');
    }

    public function getReferenceAttribute(){
        return "BMBC-" . strtoupper($this->applicationForm->slug) . "-" . str_pad($this->id,4,"0",STR_PAD_LEFT);
    }

    public function scopeInReview($query)
    {
        return $query->where('status', 'In review');
    }

    public function scopeMoreInformationRequired($query)
    {
        return $query->where('status', 'More information required');
    }

    public function getID(){
        //TODO: Replace with hash
        return $this->id;
    }

    public static function color($status){
        $colors = [
            'In progress' => 'indigo',
            'Submitted' => 'green',
            'In review' => 'yellow',
            'More information required' => 'yellow',
            'Rejected' => 'red',
            'Accepted' => 'green',
        ];

        return $colors[$status] ?? 'indigo';
    }

    public function getField($stepKey,$key)
    {
        $response = ApplicationResponse::where([
            'application_id' => $this->id,
            'step' => $stepKey,
        ])->first();
        if(!$response)
            return null;
        return $response->values[$key] ?? null;
    }

    public function getCompanyNameAttribute(){
        return $this->getField('applicant-details','businessName');
    }

    public function percentComplete(){
        $count = ApplicationResponse::where([
            'application_id' => $this->id,
        ])->count();

        return $count ? ($count/4)*100 : 0;
    }

    public function reject($notify = true){
        if($this->status != "Rejected")
        {
            $this->update([
                'status' => 'Rejected',
                'current_step' => 1,
            ]);
            if($notify)
                $this->user->notify(new ApplicationRejectedNotification($this));
        }
    }

    public function setStatus($newStatus){
        $this->update([
            'status' => $newStatus,
            'current_step' => 1,
        ]);
    }
}

app/Http/Livewire/ApplicationNotes.php
<?php

namespace App\Http\Livewire;

use App\Models\ApplicationNote;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class ApplicationNotes extends Component
{
    public $key;
    public $application;
    public $notes;

    public $noteText;

    public function mount($application,$key){
        $this->application = $application;
        $this->key = $key;
        $this->loadNotes();
    }

    public function loadNotes(){
        $this->notes = ApplicationNote::where([
            'key' => $this->key,
            'application_id' => $this->application->id,
        ])->get();
    }

    public function getShowNotesProperty(){
        if($this->application->status == "More information required")
            return true;
        if($this->application->status == "In review" && Auth::user()->can('review applications'))
            return true;

        return false;
    }

    public function render()
    {
        return view('livewire.application-notes');
    }

    public function onAddNote(){
        $this->validate([
            'noteText' => 'required'
        ],[
            'noteText.required' => 'Please enter a note.'
        ]);

        $note = ApplicationNote::create([
            'key' => $this->key,
            'application_id' => $this->application->id,
            'user_id' => Auth::user()->id,
            'note' => $this->noteText,
        ]);
        $this->noteText = null;
        $this->loadNotes();
    }
}

app/Http/Livewire/Eligibility.php
<?php

namespace App\Http\Livewire;

use App\Models\Application;
use App\Models\ApplicationForm;
use App\Notifications\ApplicationStartedNotification;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class Eligibility extends Component
{
    public $applicationForm;

    public function mount(ApplicationForm $form){
        $this->applicationForm = $form;
    }

    public $businessRates = [];
    public $barnsleyEmployeePromiseInitiative;
    public $businessSize;
    public $businessAge;
    public $businessToBusiness;
    public $financeAvailable;
    public $financialViability;
    public $restrictedSectors;
    public $stateAid;
    public $ebFunding;

    public function rules(){
        $rules = [
            "businessRates" => "required|array|min:1"
        ];
        if(in_array("Barnsley",$this->businessRates))
        {
            $rules["barnsleyEmployeePromiseInitiative"] = "required";
        }
        $rules["businessSize"] = "required";
        $rules["businessAge"] = "required";
        $rules["businessToBusiness"] = "required";
        $rules["financeAvailable"] = "required";
        $rules["financialViability"] = "required";
        $rules["restrictedSectors"] = "required";
        $rules["stateAid"] = "required";
        $rules["ebFunding"] = "required";
        return $rules;
    }

    public function onProceed()
    {
        $this->validate();

        //TODO: Select

        $app = Application::create([
            'user_id' => Auth::user()->id,
            'application_form_id' => $this->applicationForm->id,
            'status' => 'In progress'
        ]);

        //TODO: Prefill fields from profile

        Auth::user()->notify(new ApplicationStartedNotification($app));

        return redirect()->to(route('applications.apply',["form"=>$this->applicationForm,"application"=>$app]));
    }

    public function render()
    {
        return view('livewire.eligibility');
    }
}

app/Http/Livewire/FormHeader.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class FormHeader extends Component
{
    public $application;
    public $currentStep;
    public $totalSteps;
    public $navEnabled = true;

    public function onNavigate($index){
        $this->emitUp('onStep',$index);
    }

    public function render()
    {
        return view('livewire.form-header');
    }
}

app/Http/Livewire/ProductivityGrantApplicationForm.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class ProductivityGrantApplicationForm extends Component
{
    public $name = "Productivity Grant";

    public $currentStep = 1;

    public $steps = [
        'details',
        'productivity-challenge',
        'measure-productivity',
        'improve-productivity',
        'impacts',
    ];

    public $productivityImpactForm = [
        "impact" => "",
        "pre" => "",
        "post" => "",
        "timescale" => "",
    ];

    public function mount(){
        $this->currentStep = env("FORM_STEP") ?? 1;
    }

    public $productivityImpact = [
        [
            "impact" => "Example - Hours worked on support/hosting clients per month",
            "pre" => "98",
            "post" => 89,
            "timescale" => "2022",
        ],
        [

            "impact" => "Example - Productivity per hour (based on 2019/20 average)",
            "pre" => "£55.88",
            "post" => "£61.47",
            "timescale" => "2022",
        ],
    ];

    public $economicImpact = [
        [
            "impact" => "Jobs Created (FTEs)",
            "value" => "1",
            "percent_increase" => 20,
            "timescale" => "2022",
        ],
        [
            "impact" => "Jobs Safeguarded",
            "value" => "4.5",
            "percent_increase" => "n/a",
            "timescale" => "2022",
        ],
    ];

    public function render()
    {
        return view('livewire.forms.productivity-grant.' . $this->steps[$this->currentStep-1]);
    }

    public function onPrev(){
        $this->currentStep--;
    }

    public function onNext(){
        $this->currentStep++;
    }

    public function onAddProductivityImpact(){
        $this->validate([
            'productivityImpactForm.impact' => 'required|string',
            'productivityImpactForm.pre' => 'required|string',
            'productivityImpactForm.post' => 'required|string',
            'productivityImpactForm.timescale' => 'required|string',
        ],[
           'required' => "This field is required."
        ]);
        $this->productivityImpact[] = [
            "impact" => $this->productivityImpactForm['impact'],
            "pre" => $this->productivityImpactForm['pre'],
            "post" => $this->productivityImpactForm['post'],
            "timescale" => $this->productivityImpactForm['timescale'],
        ];

        $this->productivityImpactForm = [
            "impact" => "",
            "pre" => "",
            "post" => "",
            "timescale" => "",
        ];
    }

    public function onRemoveProductivityImpact($index)
    {
        unset($this->productivityImpact[$index]);
    }
}

app/Http/Livewire/ReviewApplication.php
<?php

namespace App\Http\Livewire;

use App\Models\Application;
use Livewire\Component;

class ReviewApplication extends Component
{
    public $application;

    public function mount(Application $application)
    {
        $this->application = $application;
    }

    public function render()
    {
        return view('livewire.review-application');
    }
}

resources/views/livewire/application-notes.blade.php
<div class="px-4 md:px-0 mt-8">
    @if($this->showNotes)
    <ul class="divide-y divide-gray-200">
        @foreach($notes as $note)
            <li class="py-4">
                <div class="flex space-x-3">
                    <img class="h-12 w-12 rounded-full" src="{{ $note->user->profile_photo_url }}" alt="">
                    <div class="flex-1 space-y-1">
                        <div class="flex items-center justify-between">
                            <h3 class="text-sm font-medium">
                                {{ $note->user->id == Auth::user()->id ? "You" : $note->user->name }}
                            </h3>
                            <p class="text-sm text-gray-500">
                                {{ $note->created_at->diffForHumans() }}
                            </p>
                        </div>
                        <p class="text-sm text-gray-500">
                            {{ $note->note }}
                        </p>
                    </div>
                </div>
            </li>
        @endforeach
    </ul>

    <div class="md:pl-14 border-t border-gray-200">
        <div class="mt-4">
            <x-jet-label for="total_grant_requested" value="{{ __('Note') }}" class="sr-only" />

            <x-textarea class="w-full text-sm" wire:model="noteText" placeholder="Add a note"></x-textarea>
            <x-jet-input-error for="noteText" class="mt-2" />


            <div class="flex justify-end mt-2">
                <button type="submit" wire:click="onAddNote" class="text-sm border-2 border-green-300 rounded-full text-green-500 px-3 py-1 font-bold uppercase bg-white hover:bg-green-100 hover:text-green-700">
                    Add Note
                </button>
            </div>

        </div>

    </div>
    @endif
</div>

resources/views/livewire/form-header.blade.php
<header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">

        <div class="sm:flex justify-between items-center">
            <div class="mb-4 sm:mb-0">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    {{ $application->applicationForm->name }} Application
                </h2>
                <div class="sm:flex">
                    <p class="text-xs mt-2 text-gray-600">Ref: <span class="font-bold text-gray-800">{{ $application->reference }}</span> </p>
                    @if($application->applicationForm->guidance_document)
                    <p class="text-xs mt-2 text-gray-600 sm:ml-4">Need help? <a class="underline" href="https://www.enterprisingbarnsley.co.uk/digital-innovation-grants/dig-grant-guidance/" target="_blank">Download guidance document</a></p>
                    @endif
                </div>


            </div>
            <nav class="flex sm:items-center justify-between sm:justify-center mt-2 sm:mt-0 text-gray-500" aria-label="Progress">
                <p class="text-sm font-medium">Step {{ $currentStep }} of {{ $totalSteps }}</p>
                <ol class="ml-8 flex items-center space-x-5">

                    @for ($i = 1; $i <= $totalSteps; $i++)
                        @if($currentStep > $i)
                            <li>
                                <!-- Completed Step -->
                                @if($navEnabled)
                                <a href="#" wire:click.prevent="onNavigate({{$i}})" class="block w-2.5 h-2.5 bg-red-600 rounded-full">
                                    <span class="sr-only">Step 1</span>
                                </a>
                                @else
                                    <div class="block w-2.5 h-2.5 bg-red-600 rounded-full">
                                        <span class="sr-only">Step 1</span>
                                    </div>
                                @endif
                            </li>
                        @elseif($currentStep == $i)
                            <li>

                                <!-- Current Step -->
                                @if($navEnabled)
                                <a href="#" wire:click.prevent="onNavigate({{$i}})" class="relative flex items-center justify-center" aria-current="step">
        <span class="absolute w-5 h-5 p-px flex" aria-hidden="true">
          <span class="w-full h-full rounded-full bg-red-200"></span>
        </span>
                                    <span class="relative block w-2.5 h-2.5 bg-red-600 rounded-full" aria-hidden="true"></span>
                                    <span class="sr-only">Step {{ $i }}</span>
                                </a>
                                @else
                                    <div class="relative flex items-center justify-center" aria-current="step">
        <span class="absolute w-5 h-5 p-px flex" aria-hidden="true">
          <span class="w-full h-full rounded-full bg-red-200"></span>
        </span>
                                        <span class="relative block w-2.5 h-2.5 bg-red-600 rounded-full" aria-hidden="true"></span>
                                        <span class="sr-only">Step {{ $i }}</span>
                                    </div>
                                @endif
                            </li>
                        @else
                            <li>
                                <!-- Upcoming Step -->
                                @if($navEnabled)

                                    <a href="#" wire:click.prevent="onNavigate({{$i}})" class="block w-2.5 h-2.5 bg-gray-200 rounded-full">
                                        <span class="sr-only">Step {{ $i }}</span>
                                    </a>
                                @else
                                    <div class="block w-2.5 h-2.5 bg-gray-200 rounded-full">
                                        <span class="sr-only">Step {{ $i }}</span>
                                    </div>
                                @endif
                            </li>
                        @endif
                    @endfor

                </ol>
            </nav>
        </div>
    </div>
</header>

resources/views/livewire/review-application.blade.php
<div>
    <header class="bg-white shadow">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">

            <div class="sm:flex justify-between items-center">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    Review Application #{{ $application->id }}
                </h2>
            </div>
        </div>
    </header>
</div>